### ISSUE TITLE
Make it possible for users to submit feedback

### ISSUE THREAD

**Issue by pbruvoll** [pbruvoll/tekkendocs#133]
We could have a form where users could submit feedback, about errors in frame data or feature requests. The form could post the message to a dedicated slack chanel?
Perhaps add a link to "feedback" in the footer?

**Comment by framitdavid** [comment]
@pbruvoll should we close this issue now? I saw that the PR about contacting points is merged.

**Comment by pbruvoll** [comment]
Yes, we can close this :) It could be nice for an option to submit feedback without needing to log in, but then you have the issue of dealing with spam and there are already so many other ways to get in touchwith twitter, facebook and Discord.
