### ISSUE TITLE
Move names with special characters display incorrectly

### ISSUE THREAD

**Issue by Sei-Jin** [pbruvoll/tekkendocs#143]
Moves names with special characters will display incorrectly. Some examples are:

- Jun's [Hourai's Dance](https://tekkendocs.com/t8/jun/db1,1,12) displays as `Hourai&#039;s Dance`
- Azucena's [Alegría del Café](https://tekkendocs.com/t8/azucena/R.df12) displays as `Alegra del Caf`
- Bryan's [Front Kick > Double Hammer](https://tekkendocs.com/t8/bryan/b3,12) displays as `Front Kick &gt; Double Hammer`

Reference screenshot:

![image](https://github.com/user-attachments/assets/4985169b-b5c3-488f-aeae-f938e97d4acc)

**Comment by pbruvoll** [comment]
Thanks for reporting. I'm not quite sure how to fix this yet, but I will look into it after I'm done with the next feature

**Comment by pbruvoll** [comment]
They should all be fixed now. Feel free to report if you see any more issues :)
