### ISSUE TITLE
Twitch Bot Integration

### ISSUE THREAD

**Issue by Seb0731** [pbruvoll/tekkendocs#174]
### Description

A twitch bot similar to the mokujin bot, allows someone to quickly search any move from a twitch chat. This could help both streamers and viewers learn the frame data of moves with the use of a single command, and without opening a separate tab or application.

**Comment by pbruvoll** [comment]
I don't have much experience with Twitch bots. But I know a Twitter user called Sneaky_amxx has made a twitch bot with frame data from tekkendocs.
He has a post about it here https://x.com/Sneaky_amxx/status/1756566769538572299

**Comment by pbruvoll** [comment]
I'll close this one as someone has already done this.
