### ISSUE TITLE
Move code for page selection for a character to avoid duplication

### ISSUE THREAD

**Issue by pbruvoll** [pbruvoll/tekkendocs#53]
On the top of the character page, there is a sub-page selection with "Frame data", "Guide" and "Antistrat". This component is duplicated and rendered as part of the sub page. So the code is duplicated in 
app\routes\_mainLayout.t8_.$character._index.tsx
app\routes\_mainLayout.t8_.$character.antistrat.tsx
app\routes\_mainLayout.t8_.$character.meta.tsx

It should be extracted to app\routes\_mainLayout.t8_.$character.tsx such that its the same for all sub-pages

![dup](https://github.com/pbruvoll/tekkendocs/assets/4255753/8af7ce2d-d62c-45b8-9aa0-54086b219e88)

**Comment by abhayrajput87** [comment]
hey man!! Can I work on this issue??

**Comment by pbruvoll** [comment]
@abhayrajput87 Yes, you can :)
Of the 3 places where the code is duplicated, I think the one in \app\routes\_mainLayout.t8_.$character.antistrat.tsx is the best to use since it also has an image of the character.

**Comment by abhayrajput87** [comment]
Hello @pbruvoll, I've just submitted a pull request for your review. Please take a look whenever you have a moment. Thank you!

**Comment by pbruvoll** [comment]
@abhayrajput87  Thx, I'll close this issue now.
